--------------------------------------------------------
--  File created - Saturday-May-14-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BHUSER
--------------------------------------------------------

  CREATE TABLE "TESTUSERDB"."BHUSER" 
   (	"USERID" NUMBER, 
	"JOINDATE" DATE, 
	"USERNAME" VARCHAR2(50 BYTE), 
	"USERPASSWORD" VARCHAR2(50 BYTE), 
	"MOTTO" VARCHAR2(141 BYTE), 
	"USEREMAIL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TESTUSERDB.BHUSER
SET DEFINE OFF;
Insert into TESTUSERDB.BHUSER (USERID,JOINDATE,USERNAME,USERPASSWORD,MOTTO,USEREMAIL) values (1,to_date('01-MAY-16','DD-MON-RR'),'bart','password','don''t have a cow, man!','bart@fox.net');
--------------------------------------------------------
--  DDL for Index BHUSER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTUSERDB"."BHUSER_PK" ON "TESTUSERDB"."BHUSER" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BHUSER
--------------------------------------------------------

  ALTER TABLE "TESTUSERDB"."BHUSER" ADD CONSTRAINT "BHUSER_PK" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTUSERDB"."BHUSER" MODIFY ("USEREMAIL" NOT NULL ENABLE);
  ALTER TABLE "TESTUSERDB"."BHUSER" MODIFY ("USERPASSWORD" NOT NULL ENABLE);
  ALTER TABLE "TESTUSERDB"."BHUSER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "TESTUSERDB"."BHUSER" MODIFY ("USERID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger BHUSER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TESTUSERDB"."BHUSER_TRG" 
BEFORE INSERT ON BHUSER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.USERID IS NULL THEN
      SELECT BHUSER_SEQ.NEXTVAL INTO :NEW.USERID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TESTUSERDB"."BHUSER_TRG" ENABLE;
