CREATE SEQUENCE BHPOST_SEQ
START WITH 1
INCREMENT BY 1
CACHE 10;

CREATE OR REPLACE TRIGGER BHPOST_TRG
BEFORE INSERT
ON BHPOST
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  if(:new.ID is null) then
  SELECT BHPOST_SEQ.nextval
  INTO :new.ID
  FROM dual;
  end if;
END;

ALTER TRIGGER "T_MYTABLE_ID" ENABLE;
